appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: H2sw6TuyVbH/JqVWGreRPK8TFoViAj1EslfiqbTbhkYfyS3ETmLrMSFxUlGJKSR9oytDMz9tiNhC9pF48irGAvcVSryR4CiN0UGUkNd11FKcZ/rg743SAX21kyGPjRqEfvdVF+Z9nNMK7Yb66Z44AxlOPHpZylJri3ZNlEMECJIyz13T+UxaKwp+9m+oV/tD9f0yR+qkM0zQidyAZ/6/ZXB+2zkYvNz+IuV+D8ckDZMTUAqDxNl65Ru3HfgzYoE05ocHAonnykejCUXX0Kk1TK6MmmcIzY5TdD0LLB5Sp3S/wCyu48MzKQxt8Nz7KgQDAbLLwfipyq+kE0157gprXHBlubXM6BQJTOSG8MSQ6i1RZv8k2QcYF6zdRI+2fC984qJlnyRalYiljRVK8zwRF3HGk/u+cadSI5LfXd5VQkR0dnkg9/Li+K/DM75rKLaqaim8Zvff14aSPdpcrP44RTJ3hV1/jSQUapzC3jyeu+/dopwA4wZ81wN5bKSa2CYqSMYBuonTXNuDn4m+1q6XyDZY0RpgZwgVD0kAQIbBg3Ch0Vo9aJkMIawqnm2Kim9MhI2E4u0dDukqxEg3PNoU+NoP7gw2AC5TZ8UMIWoktH7dqCCy6hvxIS+/bMDsw5+tjebfA/1Af6IAfqLderVPhsIug+55ChKKIVCojXSzUdo=}
