travis:
  secure:
    BINSTAR_TOKEN: hW+SqEEoTNwGo3lGFSAe5da3cJg485sFBsSQ0oZeEJsE8DZmQNgnmVSzNAvY96877HQ4bA2ubrm+kr0kGqHzY11uMC2i2y6qhE3K216yAHkRNjSHwbsP3PDYlxkTRky5g6s2tSvzDpLEZBSAHTShH6WGPej9gPRhRf3JMXMcCIoFlfRlD43hlH73QlsTyxlucyTEo41rVAiDXIatM81RIratXfF8PSKFzs5xiAIBNX3ltF3M611ReexCDK7a4c8G3NhOMXXqQUeVqKB2ZrON+kyL2ZvgHwQqLlhDOxetidIv/+OfxtkfocjGmkWNl+aS9r/GGLROBdQy85grBwYK2FUv5A8f5VTtidPVAh6QdcduekqvCemNAJJdNmOYCwviz6TuO5/thohHijxZfQGvZWttbnWoPvkAg4Pq82dtW14OVGqF9nKT3jHpnxuIed8DrLQiRjdVnS5YgVe+bCkIve4HQNh71wV3NbJoy9taRwwA1tYxokCJn2H17CcyDFeoHHFZQxMiQHveJKtcMVlaN04hy2rOpSfyE6+1GkoFtmw6EZbxe5KxW1s3IEDL6hVJe2SG15sERDJDH5fFhaS3I1cAJRyw3M4q0y8/pIXxgEGCasYZbM0Jd73YZ4U7GT/hvLWmrhE/1JtD4gR9qz4L06KnCoeNi2TlBEw6+0BV488=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
